baseURL = "http://example.org/"
languageCode = "en-us"
title = "MongoDB Tools"
theme = "hugo-theme-learn"

[params]
ordersectionsby = "weight"
jarname = "mongo-index-recommender-cli-schema-1.0-SNAPSHOT.jar"
title = "Index Recommendation Tool"