baseURL = "http://example.org/"
languageCode = "en-us"
title = "MongoDB Tools"
theme = "hugo-theme-learn"

[params]
ordersectionsby = "weight"
jarname = "mongo-relational-cli-schema-1.0-SNAPSHOT-all.jar"
title = "Schema Extraction Tool"